spring:
  #多环境配置
  profiles:
    active: prod
  #mysql配置
  datasource:
    url: jdbc:mysql://ip:port/dataDB
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: root


my:
  name: chenmingyu
  age: 24
